# Generated by Django 2.1.5 on 2019-02-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_uploadfilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
